In [35]:
import numpy as np
x = np.array([1, 2, 3,4,5,6])
np.vander(x)
np.vander(x, increasing=False)
print(np.vander(x, increasing=False))






[[   1    1    1    1    1    1]
 [  32   16    8    4    2    1]
 [ 243   81   27    9    3    1]
 [1024  256   64   16    4    1]
 [3125  625  125   25    5    1]
 [7776 1296  216   36    6    1]]
